travis:
  secure:
    BINSTAR_TOKEN: XLYpXMTGYFyir2WwO3wWtyCQAJoPMKbAn3kGyxvY9f/rCLS5sFQ1tX19wkiemjjGp2VLd+yzRnm3bLK2taNcn6+FBLXjwVQJs+oHLnCxI7RFbnv80jT0K15FF27+6CPfs1zJMTIn0bwH9oLzgmXnSpLcoNjf3Hha82t16nZQGKRX1xIF625yu1cy6nsJlexF59S3U/p6V+UbA0ph2XGimoOl/C1E3wx+w2D1LcqpkWjs3TovPPz/eu2Zj6WXd6/nXVQ4U0v6t76dekB7AVCUR1jO3Jcd3D5xr8n4XpDIyVRIajfEWtSHmB1hy/LvIPnOWED0i2vpN2VpUnr8sbrt1Ief+jACbIrhVptQhp1kdqBk3DVueKdHUvRRJwRpLTCs6QGqVP4eSRV9pttZ/enOnc/vq11HA3fm81OenNBiaxaoW9LX3myYtP00m36Py8uBoX51y1uaZSwSleqk5vN0CLjj0MKshyPunKh/idGIH3IYumFE2lGRfv0CXb+fzInhvlG4i8z+L5xhPASsLx6ibg5YxgCdJpEpxwBsbK1AvM1g3vfZO/waRl2fpruzjORCY9MOlDd8vZi4KXWR2S/GFSBYGJlk6wSbRkNdwhIbPeKkPjN04PJT0bDLlklStDfNTlzqME1mCmaZvCoLFdppTazB5qzrEz8EKocbs5ewdrU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
