travis:
  secure:
    BINSTAR_TOKEN: UmHXf5n8VdxJIV59sS75F9I9YDMP36zFozGmQax7yvGzUkWSG5u1PFlP+QQt4J73jaemfeRDteMiEqU0Zs6jnhkT9VXcBe5H6VLdPmQUm29DhXysCHX5yhTyujrATBcaj1BNVSZvMw0HYXBelbEn4ydIikyEZ9SQFFoTvOto+J6Zm7uJKU3i+3j8inYEnJoImnQ7YZHXCX4XkBC9poaznccdWGwwyOysvEt62Rl1hRQZP5w/QwVnMJLyaXu9rJc0gFpV0iux7pcBeimyyLgASVfoLjTBiNC1tGmQ4LsKQp95/VyGlv+v2mTJPIcTpIdDBKwamuD4M6RlRaeXB/2yve3uM1sc7D+2XarnuW5LkiBm3X4KwYYdFfk77HfnnN+/yVfkWv2S4LhlHaKpaFERYHM/U6Krt/9gq+lss+WgZDsFVXqY0H8I3KQhgK2rBHPZt641eUbuhSDyksD+olTcp9sILpOcNTfDLAC4xK7+19kl3/kgBOHPLpHDMJI6O/L6mKzdiNJnY18hKTyNICp3DjRICKImrKTZBDqTI+hMMOwCshmptJae3/AdqEKb802c1rzRUolX+a3Xx1Q73wH8Buea5Pm1OIVUdeiqUKerqdMtq4tDIm0YGA+LpGj7Y7LwfJo9vWMLkwGSZDnufiSLSSYx41MsOfWBsOFNChd4tBI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
